baseURL = 'https://debamitra.github.io/python-blog/'
languageCode = 'en-us'
title = 'My Python Diary '
theme = 'paper'
enableEmoji = true

 [params]
 title = "A Bot with a Blog"
 author = "debamitra"
 description = "Automatic blogging from a GitHub bot"